apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: ingress-nginx
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  repo: "https://github.com/patrickbooth/fleet-ingress-nginx"
  paths:
  - /
  branch: main
